url: https://connect-labs.github.io
baseurl: /

# Site settings
title: ConnectLabs
email: brian@connectlabs.io
description: "meta description"
intro: this is the intro message
portfolio-description: we are doing some stuff
team-intro: we are cool blablabla 
team-description: We do what we do because can. Try and stop us.

# Services offered
services:
- type: make some cool stuff
  description: pretty explainatory
  icon: fa-shopping-cart
- type: make more cool stuff
  description: pretty explainatory
  icon: fa-barcode
- type: make even more cool stuff
  description: pretty explainatory
  icon: fa-bell

# Story lines
events:
  - date: January 2017
    image: 1.jpg
    title: The start
    description: everything started here
  - date: March 2017
    image: 2.jpg
    title: It continued
    description: even more stuff happened
  - date: December 2017
    image: 3.jpg
    title: It progressed
    description: stuff continued to happened

# Team members
people:
- name: Brian Larry
  pic: 2
  position: Chief Executive Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Anthony Ferre
  pic: 2
  position: Chief Technology Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
- name: Josh Christy
  pic: 2
  position: Chief Financial Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# partner info
partners:
  - site: https://www.apple.com
    image: envato.jpg
  - site: https://www.apple.com
    image: envato.jpg
  - site: https://www.apple.com
    image: envato.jpg

# Social networks
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url: https://www.facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket 
    url: http://bitbucket.org
  - title: github
    url: http://github.com
  - title: instagram
    url: https://www.instagram.com

# Address
address:
  - line: 300 Northern Pacific Ave, Suite 101
  - line: Fargo,ND,58102

# Build settings
markdown: kramdown
permalink: pretty
